services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: hoteldb
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"
  hotel-management:
    container_name: hotel-management
    build:
      context: ./
      dockerfile: Dockerfile
    image: qlks:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb:
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/hoteldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678